### ISSUE TITLE
Could this be used to upload to iTunes Connect?

### ISSUE THREAD

**Issue by dsernst** [ekreative/xcode-build-tools#3]
I see you have http://testbuild.rocks hardcoded as the destination for `upload-ipa`. Do you know if this script could be modified to upload to iTunes Connect, instead of going through Xcode?

**Comment by mcfedr** [comment]
I haven't looked at this. There is presumably some authentication needed, maybe that's it. I would be open to pull requests to make this more flexible. Also check out fastlane - the toolchain is quite big and lacking flexibility in places but might be what you need.

**Comment by dsernst** [comment]
Sounds good, thank you.
